### oikea salasana
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "derk",
    "password": "fuark"
}

### väärä salasana
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "erk",
    "password": "shoite"
}

### myrtti login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "myrtti",
    "password": "aurinko"
}

### Get my user info TEMPLATE
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer <put-your-token-from-login-response-here>

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MCwibmFtZSI6Im15cnR0aSIsInVzZXJuYW1lIjoibXlydHRpIiwiZW1haWwiOiJteXJ0dGlAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDM1OTE2NDUsImV4cCI6MTc0MzY3ODA0NX0.6c0ygyaraE9FzICpDuZzyYsjm64RFCSiuPSeW2JtHfQ
