### oikea salasana
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "derk",
    "password": "fuark"
}

### väärä salasana
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "erk",
    "password": "shoite"
}

