POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "myrtti",
    "username": "myrtti",
    "password": "aurinko",
    "email": "myrtti@gmail.com"
}

### test users get
GET http://localhost:3000/api/v1/users

### test delete user by id
DELETE http://localhost:3000/api/v1/users/3609
